AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Marcin's NestJS API
Parameters:
  BasicResourcesStackName:
    Type: String
    Default: basic-resources-nestjs-course
  PgHost:
    Type: String
  SubnetA:
    Type: String
  SubnetB:
    Type: String
  SubnetC:
    Type: String
  SecurityGroup:
    Type: String
  CertificateArn:
    Type: String
  Domain:
    Type: String
  HostedZoneId:
    Type: String
  Environment:
    Type: String
  StaticCloudFrontHostedZoneId:
    Type: String
Resources:
  NestApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-east-1.amazonaws.com/artifacts-dev-marcin-kurs/infrastructure/44b072efe22ae37c00c35023332c6899.template
      Parameters:
        Environment:
          Ref: Environment
        HostedZoneId:
          Ref: HostedZoneId
        Domain:
          Ref: Domain
        CertificateArn:
          Ref: CertificateArn
        SecurityGroup:
          Ref: SecurityGroup
        PgHost:
          Ref: PgHost
        SubnetA:
          Ref: SubnetA
        SubnetB:
          Ref: SubnetB
        SubnetC:
          Ref: SubnetC
    Metadata:
      SamResourceId: NestApi
  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-east-1.amazonaws.com/artifacts-dev-marcin-kurs/infrastructure/b73217d4e6329d7269d4c9e35b23d438.template
      Parameters:
        DomainName:
          Fn::Sub: mpapiez-admin.${Domain}
        CertificateArn:
          Ref: CertificateArn
        HostedZoneId:
          Ref: HostedZoneId
        StaticCloudFrontHostedZoneId:
          Ref: StaticCloudFrontHostedZoneId
    Metadata:
      SamResourceId: Frontend
